### ISSUE TITLE
Mismatching folder names 'config' vs. 'configs'

### ISSUE THREAD

**Issue by matthias-brucklacher** [catalys1/mae-pytorch#2]
It's a small error, but the CLI commands refer to a folder 'configs', while the actual folder name is 'config':

![image](https://github.com/catalys1/mae-pytorch/assets/99026769/28a2bb93-bd82-4a2d-9db4-2881ec9b7c73)

 vs. 

![image](https://github.com/catalys1/mae-pytorch/assets/99026769/bab343aa-40f1-47b3-b354-8bda4c4f3de8)

**Comment by catalys1** [comment]
Fixed. Thanks for pointing that out.
